### ISSUE TITLE
Add "Why" section to README.md

### ISSUE THREAD

**Issue by eamondo2** [stevengreens10/MinecraftDrive#1]
I feel it would be helpful for you to add a "Why" section to the readme, to explain why such a cursed thing has been created.

/s

**Comment by stevengreens10** [comment]
One day when all of the hard drives, all of the SSDs, all of the floppy disks stop working.. there will be only Minecraft. There will be only blocks. Blocks as far as the eye can see. When that day comes I will be ready. I welcome this new block based society. I believe the real question is: why hasn't this been created sooner? Am I the only one who sees our impending doom? 

I will be remembered for my contributions when the time comes.

Closing as won't fix.
